M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu24.04.1} date 2026-03-23T21:41:57-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-23T21:41:57-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X6.25Y8.0
X33.25Y48.5
X89.25Y8.0
M30
